#pragma once


//Tên ứng dụng
#define WINDOW_CLASS_NAME L"Aladin"
#define MAIN_WINDOW_TITLE L"Aladin"
//Màu background, kích cỡ màn hình
#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 400

//Framerate tối đa
#define MAX_FRAME_RATE 90

//
enum Stage {
	STAGE_1,
	STAGE_2,
	STAGE_BOSS_1,
	STAGE_BOSS_2
};
enum ObjectType
{
	DEFAULT,
	GROUND,
	APPLE,
	ON_BUTTON,
	RIVER,
	SWING
};
//TiledMap
//
// MAP
//#define BACKGROUND_1 L"Resources\\TiledMap\\Map-Charleston.png"
#define BACKGROUND_1 L"Resources\\Map\\SultansDungeonBackGround1.png"
#define BACKGROUND_2 L"Resources\\Map\\SultansDungeonBackGround2.png"
#define BACKGROUND_BOSS_1 L"Resources\\Map\\final1.png"
#define BACKGROUND_BOSS_2 L"Resources\\Map\\final2.png"
// TILE
#define TILES_MATRIX_STAGE_1 L"Resources\\TiledMap\\map-copy.txt"
#define TILES_MATRIX_STAGE_2 L"Resources\\TiledMap\\Map-Pittsburgh-Matrix.txt"
#define TILES_MATRIX_STAGE_BOSS_1 L"Resources\\TiledMap\\Map-Boss1-Matrix.txt"
#define TILES_MATRIX_STAGE_BOSS_2 L"Resources\\TiledMap\\Map-Boss2-Matrix.txt"

#define TILES_MATRIX_DELIMITER ","
#define TILES_WIDTH_PER_TILE	16
#define TILES_HEIGHT_PER_TILE	16
#define TILES_TRANSCOLOR D3DCOLOR_XRGB(255, 0, 255)

#define GRID_SIZE 64
#define GRID_MAX_X 48
#define GRID_MAX_Y 5

//Giá trị tốc độ đi, tốc độ nhảy, trọng lực
#define ALADIN_WALK_SPEED		0.25f
#define ALADIN_JUMP_SPEED_Y		0.8f
#define ALADIN_GRAVITY			0.025f

// Animation của aladin
#define ALADIN_ANI_IDLE 0
#define ALADIN_ANI_ACTION_WHEN_STAND 1
#define ALADIN_ANI_CHERRY_EXPLOSION 2
#define ALADIN_ANI_PLAY_WITH_CHERRY 3 
#define ALADIN_ANI_THROW_CHERRY_WHEN_STANDING 4
#define ALADIN_ANI_ATTACK 5
#define ALADIN_ANI_LOOP_5X 6
#define ALADIN_ANI_LOOK_UP 7
#define ALADIN_ANI_SIT_DOWN 8
#define ALADIN_ANI_THROW_CHERRY_WHEN_SIT_DOWN 9
#define ALADIN_ANI_ATTACK_WHEN_SIT_DOWN 10
#define ALADIN_ANI_JUMP_WHEN_PRESSING_LEFT_OR_RIGHT_ARROW 11
#define ALADIN_ANI_JUMP_WITH_NO_KEY_PRESS 12
#define ALADIN_ANI_FALLING_DOWN 13
#define ALADIN_ANI_THROW_CHERRY_WHEN_IN_THE_AIR 14
#define ALADIN_ANI_ATTACK_WHEN_IN_THE_AIR 15
#define ALADIN_ANI_HANH_DONG_TREN_KHONG_KHI_BAT_MOT_DON_BAY 16
#define ALADIN_ANI_RUN 17
#define ALADIN_ANI_STOP 18
#define ALADIN_ANI_CLIMB_THE_LADDER 19
#define ALADIN_ANI_CLIMB_THE_ROPE 20
#define ALADIN_ANI_ACTION_WHEN_STOP_ON_THE_ROPE 21
#define ALADIN_ANI_THROW_CHERRY_WHEN_ON_THE_ROPE 22
#define ALADIN_ANI_ATTACK_WHEN_ON_THE_ROPE 23
#define ALADIN_ANI_JUMP_OUT_FROM_THE_ROPE 24
#define ALADIN_ANI_PUSH 25
#define ALADIN_ANI_XXX 26
#define ALADIN_ANI_DANG_O_TREN_THAM_BAY 27
#define ALADIN_ANI_NAP_KHI_TREN_THAM_BAY 28
#define ALADIN_ANI_GET_HIT 29
#define ALADIN_ANI_DIE 30
#define ALADIN_ANI_GET_BACK_FROM_THE_DEATH 31
#define ALADIN_ANI_COMPLETE_LEVEL 32
#define ALADIN_ANI_FLY_IN_THE_NIGHT 33
#define ALADIN_ANI_KISS 34


#define ALADIN_TEXTURE_LOCATION L"Resources\\Aladin\\aladin.png"
#define ALADIN_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(255, 0, 255)
#define ALADIN_SPRITE_WIDTH 44
#define ALADIN_SPRITE_HEIGHT 50

#define ANIMBRICK_TEXTURE_LOCATION L"Resources\\GameItem\\animbrick.png"
#define ANIMBRICK_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define ANIMBRICK_SPRITE_WIDTH 44
#define ANIMBRICK_SPRITE_HEIGHT 50

#define ANIMBALL_TEXTURE_LOCATION L"Resources\\GameItem\\animball.png"
#define ANIMBALL_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define ANIMBALL_SPRITE_WIDTH 44
#define ANIMBALL_SPRITE_HEIGHT 50

#define ANIMNAIL_TEXTURE_LOCATION L"Resources\\GameItem\\animnail.png"
#define ANIMNAIL_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define ANIMNAIL_SPRITE_WIDTH 44
#define ANIMNAIL_SPRITE_HEIGHT 50

#define ENEMY1_TEXTURE_LOCATION L"Resources\\Enemy\\Enemies_Sprite_1.png"
#define ENEMY1_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(120, 193, 152)
#define ENEMY1_SPRITE_WIDTH 44
#define ANIMNAIL_SPRITE_HEIGHT 50

#define ENEMY2_TEXTURE_LOCATION L"Resources\\Enemy\\Enemies_Sprite_1.png"
#define ENEMY2_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(120, 193, 152)
#define ENEMY2_SPRITE_WIDTH 44
#define ENEMY2_SPRITE_HEIGHT 50

#define ENEMY3_TEXTURE_LOCATION L"Resources\\Enemy\\Enemies_Sprite_1.png"
#define ENEMY3_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(120, 193, 152)
#define ENEMY3_SPRITE_WIDTH 44
#define ENEMY3_SPRITE_HEIGHT 50

#define SCOREOBJECT1_TEXTURE_LOCATION L"Resources\\GameItem\\scoreobject1.png"
#define SCOREOBJECT1_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define SCOREOBJECT1_SPRITE_WIDTH 44
#define SCOREOBJECT1_SPRITE_HEIGHT 50

#define SCOREOBJECT2_TEXTURE_LOCATION L"Resources\\GameItem\\scoreobject2.png"
#define SCOREOBJECT2_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define SCOREOBJECT2_SPRITE_WIDTH 44
#define SCOREOBJECT2_SPRITE_HEIGHT 50

#define APPLE_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(248, 0, 248)
#define SCOREOBJECT1_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(248, 0, 248)
#define CHAIN_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define STAIR_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define EGG_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(248, 0, 248)
#define BOTTLE_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(248, 0, 248)
#define WALL_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define ROOF_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
#define POLE_TEXTURE_TRANS_COLOR D3DCOLOR_XRGB(163, 73, 164)
//Animation của Shield
#define SHIELD_SIDE 0
#define SHIELD_CENTER 1
#define SHIELD_UP 2
#define SHIELD_DOWN 3

#define SHIELD_WIDTH 16
#define SHIELD_HEIGHT 16
#define SHIELD_SPEED 0.125f

struct BoundingBox
{
	float x, y;
	float width, height;
	float vx = 0, vy = 0;
	float dt = 0;
	int direction;
};
